# Generated by Django 4.2.11 on 2024-05-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='a', upload_to='images/'),
            preserve_default=False,
        ),
    ]
